### ISSUE TITLE
Tests consistently fail duel to check for `nmcli`

### ISSUE THREAD

**Issue by masih** [functionland/go-fula#129]
`wap` wifi package fails if `nmcli` is not found in path. This causes tests across the entire repo to fail.

See:
 - https://github.com/functionland/go-fula/blob/c6ce37d7fdf13f1a5d079362509a94c5d8ab0f4d/wap/pkg/wifi/init.go#L25

**Comment by ehsan6sha** [comment]
commented that check out for now
