### ISSUE TITLE
fula mobile android not work on WIFI

### ISSUE THREAD

**Issue by farhoud** [functionland/go-fula#41]
- https://github.com/golang/go/issues/52702

**Comment by farhoud** [comment]
It's not this network problem it's a DNS problem.
For some reason on Android and on WIFI can not resolve bootsrap.libp2p.io.
So for now I deploy 2 nodes on AWS as bootstrap.

**Comment by ehsan6sha** [comment]
bootsrap.libp2p.io is the public libp2p node for bootstrapping instances?

**Comment by farhoud** [comment]
@ehsan6sha 
default bootstrap nodes are :
	"/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
	"/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
	"/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
	"/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
I think `/dnsaddr` is made by libp2p guys because:
bootstrap.libp2p.io does not have A or AAA record it has TXT record of another list of addresses.
