### ISSUE TITLE
Expose controls for opportunistic push

### ISSUE THREAD

**Issue by masih** [functionland/go-fula#94]
fulamobile should enable the app to push things opportunistically and continue to work when no internet is available to push DAGs out to blox.

Changes:

- `Put` does not throw an error if it cannot push.
- `instead` it would capture all the CIDs it failed to push and expose them via an API that returns the list of such CIDs.
- There is already a Push function that takes a CID and pushes it explicitly.
- The mobile app can then, depending on whenever there is connectivity, could get that list, and for each CID call Push explicitly.

The reason the opportunistic logic should live in app level is because, app has access to Mobile OS APIs that should give it much richer information to take decisions, and even be able to run stuff as background processes in the app.

**Comment by ehsan6sha** [comment]
@masih I think this is addressed already?

**Comment by ehsan6sha** [comment]
already resolved with failedActions
